[package]
authors.workspace = true
description = "The Torrust Tracker API."
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["axum", "bittorrent", "http", "server", "torrust", "tracker"]
license.workspace = true
name = "torrust-axum-rest-tracker-api-server"
publish.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aquatic_udp_protocol = "0"
axum = { version = "0", features = ["macros"] }
axum-extra = { version = "0", features = ["query"] }
axum-server = { version = "0", features = ["tls-rustls-no-provider"] }
bittorrent-http-tracker-core = { version = "3.0.0-develop", path = "../http-tracker-core" }
bittorrent-primitives = "0.1.0"
bittorrent-tracker-core = { version = "3.0.0-develop", path = "../tracker-core" }
bittorrent-udp-tracker-core = { version = "3.0.0-develop", path = "../udp-tracker-core" }
derive_more = { version = "2", features = ["as_ref", "constructor", "from"] }
futures = "0"
hyper = "1"
reqwest = { version = "0", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_with = { version = "3", features = ["json"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
torrust-axum-server = { version = "3.0.0-develop", path = "../axum-server" }
torrust-rest-tracker-api-client = { version = "3.0.0-develop", path = "../rest-tracker-api-client" }
torrust-rest-tracker-api-core = { version = "3.0.0-develop", path = "../rest-tracker-api-core" }
torrust-server-lib = { version = "3.0.0-develop", path = "../server-lib" }
torrust-tracker-clock = { version = "3.0.0-develop", path = "../clock" }
torrust-tracker-configuration = { version = "3.0.0-develop", path = "../configuration" }
torrust-tracker-metrics = { version = "3.0.0-develop", path = "../metrics" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
torrust-tracker-swarm-coordination-registry = { version = "3.0.0-develop", path = "../swarm-coordination-registry" }
torrust-udp-tracker-server = { version = "3.0.0-develop", path = "../udp-tracker-server" }
tower = { version = "0", features = ["timeout"] }
tower-http = { version = "0", features = ["compression-full", "cors", "propagate-header", "request-id", "trace"] }
tracing = "0"
url = "2"

[dev-dependencies]
local-ip-address = "0"
mockall = "0"
torrust-rest-tracker-api-client = { version = "3.0.0-develop", path = "../rest-tracker-api-client" }
torrust-tracker-test-helpers = { version = "3.0.0-develop", path = "../test-helpers" }
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
