[package]
description = "A library with the primitive types shared by the Torrust tracker packages."
keywords = ["api", "library", "metrics"]
name = "torrust-tracker-metrics"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono = { version = "0", default-features = false, features = ["clock"] }
derive_more = { version = "2", features = ["constructor"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2"
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
tracing = "0.1.41"

[dev-dependencies]
approx = "0.5.1"
formatjson = "0.3.1"
pretty_assertions = "1.4.1"
rstest = "0.25.0"
