[package]
authors.workspace = true
description = "A library with the core functionality needed to implement a BitTorrent HTTP tracker."
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["api", "bittorrent", "core", "library", "tracker"]
license.workspace = true
name = "bittorrent-http-tracker-core"
publish.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aquatic_udp_protocol = "0"
bittorrent-http-tracker-protocol = { version = "3.0.0-develop", path = "../http-protocol" }
bittorrent-primitives = "0.1.0"
bittorrent-tracker-core = { version = "3.0.0-develop", path = "../tracker-core" }
criterion = { version = "0.5.1", features = ["async_tokio"] }
futures = "0"
serde = "1.0.219"
thiserror = "2"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
tokio-util = "0.7.15"
torrust-tracker-clock = { version = "3.0.0-develop", path = "../clock" }
torrust-tracker-configuration = { version = "3.0.0-develop", path = "../configuration" }
torrust-tracker-events = { version = "3.0.0-develop", path = "../events" }
torrust-tracker-metrics = { version = "3.0.0-develop", path = "../metrics" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
torrust-tracker-swarm-coordination-registry = { version = "3.0.0-develop", path = "../swarm-coordination-registry" }
tracing = "0"

[dev-dependencies]
formatjson = "0.3.1"
mockall = "0"
serde_json = "1.0.140"
torrust-tracker-test-helpers = { version = "3.0.0-develop", path = "../test-helpers" }

[[bench]]
harness = false
name = "http_tracker_core_benchmark"
