[package]
description = "A library to a clock for the torrust tracker."
keywords = ["clock", "library", "torrents"]
name = "torrust-tracker-clock"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
chrono = { version = "0", default-features = false, features = ["clock"] }
lazy_static = "1"
tracing = "0"

torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }

[dev-dependencies]
