[package]
authors.workspace = true
description = "A library with the core functionality needed to implement a BitTorrent UDP tracker."
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["api", "bittorrent", "core", "library", "tracker"]
license.workspace = true
name = "torrust-rest-tracker-api-core"
publish.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bittorrent-http-tracker-core = { version = "3.0.0-develop", path = "../http-tracker-core" }
bittorrent-tracker-core = { version = "3.0.0-develop", path = "../tracker-core" }
bittorrent-udp-tracker-core = { version = "3.0.0-develop", path = "../udp-tracker-core" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
tokio-util = "0.7.15"
torrust-tracker-configuration = { version = "3.0.0-develop", path = "../configuration" }
torrust-tracker-metrics = { version = "3.0.0-develop", path = "../metrics" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
torrust-tracker-swarm-coordination-registry = { version = "3.0.0-develop", path = "../swarm-coordination-registry" }
torrust-udp-tracker-server = { version = "3.0.0-develop", path = "../udp-tracker-server" }

[dev-dependencies]
torrust-tracker-events = { version = "3.0.0-develop", path = "../events" }
torrust-tracker-test-helpers = { version = "3.0.0-develop", path = "../test-helpers" }
