[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[tracker]
token = "MyAccessToken"

[auth]
user_claim_token_pepper = "MaxVerstappenWC2021"

[database]
connect_url = "mysql://root:root_secret_password@mysql:3306/torrust_index"

[mail.smtp]
port = 1025
server = "mailcatcher"

[registration]
[registration.email]
